### ISSUE TITLE
another build error

### ISSUE THREAD

**Issue by dnns92** [zhou13/neurvps#3] opened 2019-10-31 20:19 UTC
Dear zhou,

first of all, thanks for the work you put into this. However, when I try to evaluate the pre-build models, i get the following error after I ran through your step-by-step tutorial. To me this error is very uninformative. I checked on the internet, but was not finding helpful information. It seems to be related to the build process I guess.
cuda.is_available is True.
I run the latest torch on cuda 10.1 on windows.

Do you have any ideas that could show me where the actual error occurs? Thank you very much in advance.

Cheers,

Dennis

{... some infos on the network...}
Let's use 1 GPU(s)!
Traceback (most recent call last):
File "C:\Users\denno\AppData\Local\Continuum\anaconda3\envs\neurvps\lib\site-packages\torch\utils\cpp_extension.py", line 1030, in _build_extension_module
check=True)
File "C:\Users\denno\AppData\Local\Continuum\anaconda3\envs\neurvps\lib\subprocess.py", line 487, in run
output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "eval.py", line 185, in
main()
File "eval.py", line 86, in main
model, C.model.output_stride, C.model.upsample_scale
File "W:\neurvps-master\neurvps\models\vanishing_net.py", line 23, in init
self.anet = ApolloniusNet(output_stride, upsample_scale)
File "W:\neurvps-master\neurvps-master\neurvps\models\vanishing_net.py", line 90, in init
self.conv00 = ConicConv(32, 32)
File "W:\neurvps-master\neurvps-master\neurvps\models\conic.py", line 19, in init
bias=bias,
File "W:\neurvps-master\neurvps-master\neurvps\models\deformable.py", line 132, in init
DCN = load_cpp_ext("DCN")
File "W:\neurvps-master\neurvps-master\neurvps\models\deformable.py", line 29, in load_cpp_ext
build_directory=tar_dir,
File "C:\Users\denno\AppData\Local\Continuum\anaconda3\envs\neurvps\lib\site-packages\torch\utils\cpp_extension.py", line 661, in load
is_python_module)
File "C:\Users\denno\AppData\Local\Continuum\anaconda3\envs\neurvps\lib\site-packages\torch\utils\cpp_extension.py", line 830, in jit_compile
with_cuda=with_cuda)
File "C:\Users\denno\AppData\Local\Continuum\anaconda3\envs\neurvps\lib\site-packages\torch\utils\cpp_extension.py", line 883, in write_ninja_file_and_build
build_extension_module(name, build_directory, verbose)
File "C:\Users\denno\AppData\Local\Continuum\anaconda3\envs\neurvps\lib\site-packages\torch\utils\cpp_extension.py", line 1046, in build_extension_module
raise RuntimeError(message)
RuntimeError: Error building extension 'DCN': [1/3] C:\Users\denno\AppData\Local\Continuum\anaconda3\Library\bin\bin\nvcc -Xcompiler /EHsc -Xcompiler /wd4819 -Xcompiler /MD -DTORCH_EXTENSION_NAME=DCN -DTORCH_API_INCLUDE_EXTENSION_H -IC:\Users\denno\AppData\Local\Continuum\anaconda3\envs\neurvps\lib\site-packages\torch\include -IC:\Users\denno\AppData\Local\Continuum\anaconda3\envs\neurvps\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\denno\AppData\Local\Continuum\anaconda3\envs\neurvps\lib\site-packages\torch\include\TH -IC:\Users\denno\AppData\Local\Continuum\anaconda3\envs\neurvps\lib\site-packages\torch\include\THC -IC:\Users\denno\AppData\Local\Continuum\anaconda3\Library\bin\include -IC:\Users\denno\AppData\Local\Continuum\anaconda3\envs\neurvps\Include -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS -D__CUDA_NO_HALF_CONVERSIONS -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_50,code=sm_50 -c W:\ML\vanishingPointDetection\neurvps-master\neurvps\models\cpp\deform_conv_cuda.cu -o deform_conv_cuda.cuda.o
FAILED: deform_conv_cuda.cuda.o
C:\Users\denno\AppData\Local\Continuum\anaconda3\Library\bin\bin\nvcc -Xcompiler /EHsc -Xcompiler /wd4819 -Xcompiler /MD -DTORCH_EXTENSION_NAME=DCN -DTORCH_API_INCLUDE_EXTENSION_H -IC:\Users\denno\AppData\Local\Continuum\anaconda3\envs\neurvps\lib\site-packages\torch\include -IC:\Users\denno\AppData\Local\Continuum\anaconda3\envs\neurvps\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\denno\AppData\Local\Continuum\anaconda3\envs\neurvps\lib\site-packages\torch\include\TH -IC:\Users\denno\AppData\Local\Continuum\anaconda3\envs\neurvps\lib\site-packages\torch\include\THC -IC:\Users\denno\AppData\Local\Continuum\anaconda3\Library\bin\include -IC:\Users\denno\AppData\Local\Continuum\anaconda3\envs\neurvps\Include -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_50,code=sm_50 -c W:\ML\vanishingPointDetection\neurvps-master\neurvps\models\cpp\deform_conv_cuda.cu -o deform_conv_cuda.cuda.o
CreateProcess failed: The system cannot find the file specified.
ninja: fatal: ReadFile: The handle is invalid

The build ninja file states:

ninja_required_version = 1.3
cxx = cl
nvcc = C:\Users\denno\AppData\Local\Continuum\anaconda3\Library\bin\bin\nvcc

cflags = -DTORCH_EXTENSION_NAME=DCN -DTORCH_API_INCLUDE_EXTENSION_H -IC:\Users\denno\AppData\Local\Continuum\anaconda3\envs\neurvps\lib\site-packages\torch\include -IC:\Users\denno\AppData\Local\Continuum\anaconda3\envs\neurvps\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\denno\AppData\Local\Continuum\anaconda3\envs\neurvps\lib\site-packages\torch\include\TH -IC:\Users\denno\AppData\Local\Continuum\anaconda3\envs\neurvps\lib\site-packages\torch\include\THC -IC:\Users\denno\AppData\Local\Continuum\anaconda3\Library\bin\include -IC:\Users\denno\AppData\Local\Continuum\anaconda3\envs\neurvps\Include -D_GLIBCXX_USE_CXX11_ABI=0 /MD /wd4819 /EHsc -O3
cuda_flags = -Xcompiler /EHsc -Xcompiler /wd4819 -Xcompiler /MD -DTORCH_EXTENSION_NAME=DCN -DTORCH_API_INCLUDE_EXTENSION_H -IC:\Users\denno\AppData\Local\Continuum\anaconda3\envs\neurvps\lib\site-packages\torch\include -IC:\Users\denno\AppData\Local\Continuum\anaconda3\envs\neurvps\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\denno\AppData\Local\Continuum\anaconda3\envs\neurvps\lib\site-packages\torch\include\TH -IC:\Users\denno\AppData\Local\Continuum\anaconda3\envs\neurvps\lib\site-packages\torch\include\THC -IC:\Users\denno\AppData\Local\Continuum\anaconda3\Library\bin\include -IC:\Users\denno\AppData\Local\Continuum\anaconda3\envs\neurvps\Include -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_50,code=sm_50
ldflags = /DLL c10.lib torch.lib torch_python.lib _C.lib /LIBPATH:C:\Users\denno\AppData\Local\Continuum\anaconda3\envs\neurvps\libs /LIBPATH:C:\Users\denno\AppData\Local\Continuum\anaconda3\envs\neurvps\lib\site-packages\torch\lib /LIBPATH:C:\Users\denno\AppData\Local\Continuum\anaconda3\Library\bin\lib/x64 cudart.lib

rule compile
command = cl /showIncludes $cflags -c $in /Fo$out
deps = msvc

rule cuda_compile
command = $nvcc $cuda_flags -c $in -o $out

rule link
command = "C$:\Program Files (x86)\Microsoft Visual Studio 15.0\VC\Tools\MSVC\14.12.25827\bin\Hostx64\x64/link.exe" $in /nologo $ldflags /out:$out

build deform_conv_cuda.cuda.o: cuda_compile W$:\neurvps-master\neurvps-master\neurvps\models\cpp\deform_conv_cuda.cu
build deform_conv.o: compile W$:\neurvps-master\neurvps-master\neurvps\models\cpp\deform_conv.cpp

build DCN.pyd: link deform_conv_cuda.cuda.o deform_conv.o

default DCN.pyd

edit: minor changes

**Comment by zhou13** [comment] 2019-11-02 10:41
We did not test it on the windows platform. For what I read, it seems that PyTorch cannot find `C:\Users\denno\AppData\Local\Continuum\anaconda3\Library\bin\bin\nvcc`. To get more errors, you can comment out https://github.com/zhou13/neurvps/blob/e2f8d19114dd6785ebfa95dbfb11d34ede6c908e/neurvps/models/deformable.py#L21 and add `verbose=True` to `load_cpp_ext`.

**Comment by zhou13** [comment] 2019-11-06 14:44
I will close this issue since `load_cpp_ext` is fairly common to build cpp extensions for PyTorch. It is likely that the problem is due to the installation or windows platform. Feel free to reopen the issue if you have any updates.

**Closed by zhou13** 2019-11-06 14:44 UTC
Labels: question
